slider_data = {
    "Environment & Energy": {
        "Fossil Fuel Consumption": {"init": 70, "connections": {"Carbon Emissions": 0.8, "Air Quality": -0.5, "Global Energy Prices": 0.6}},
        "Carbon Emissions": {"init": 80, "connections": {"Global Temperature": 0.9, "Ocean Acidification": 0.7, "Air Quality": -0.8}},
        "Air Quality": {"init": 60, "connections": {"Healthcare Access": -0.3, "Fossil Fuel Consumption": 0.5, "Carbon Emissions": -0.8}},
        "Global Temperature": {"init": 90, "connections": {"Sea Level Rise": 0.95, "Species Biodiversity": -0.6, "Sustainable Agriculture": -0.2}},
        "Sea Level Rise": {"init": 70, "connections": {"Economic Growth": -0.1}},
        "Investment in Renewable Energy": {"init": 40, "connections": {"Fossil Fuel Consumption": -0.7, "Renewable Energy Production": 0.9, "Economic Growth": 0.2}},
        "Deforestation Rate": {"init": 60, "connections": {"Species Biodiversity": -0.8, "Carbon Emissions": 0.4, "Agricultural Land Use": 0.6}},
        "Species Biodiversity": {"init": 30, "connections": {"Food Security": -0.4, "Deforestation Rate": -0.8, "Ocean Acidification": -0.5}},
        "Ocean Acidification": {"init": 75, "connections": {"Species Biodiversity": -0.5, "Food Security": -0.3}},
        "Methane Emissions": {"init": 65, "connections": {"Global Temperature": 0.3, "Air Quality": -0.2}},
        "Plastic Pollution": {"init": 85, "connections": {"Ocean Acidification": 0.6, "Species Biodiversity": -0.4}},
        "Water Usage": {"init": 55, "connections": {"Agricultural Land Use": 0.7, "Food Security": -0.2}},
        "Renewable Energy Production": {"init": 35, "connections": {"Fossil Fuel Consumption": -0.6, "Energy Efficiency": 0.5}},
        "Energy Efficiency": {"init": 45, "connections": {"Fossil Fuel Consumption": -0.4, "Industrial Output": 0.3}},
        "Sustainable Agriculture": {"init": 40, "connections": {"Food Security": 0.7, "Deforestation Rate": -0.3, "Water Usage": -0.2}},
    },
    "Economy": {
        "Economic Growth": {"init": 60, "connections": {"Unemployment Rate": -0.5, "Industrial Output": 0.7, "Inflation Rate": 0.3}},
        "Unemployment Rate": {"init": 40, "connections": {"Economic Growth": -0.6, "Social Stability": -0.2, "Income Inequality": 0.4}},
        "Global Energy Prices": {"init": 70, "connections": {"Inflation Rate": 0.6, "Industrial Output": -0.4, "Fossil Fuel Consumption": 0.8}},
        "Income Inequality": {"init": 65, "connections": {"Social Stability": -0.7, "Economic Growth": -0.2, "Crime Rate": 0.5}},
        "Industrial Output": {"init": 55, "connections": {"Economic Growth": 0.7, "Energy Efficiency": 0.3, "Resource Scarcity": -0.2}},
        "Resource Scarcity": {"init": 80, "connections": {"Global Energy Prices": 0.4, "Industrial Output": -0.3, "Food Security": -0.1}},
        "Trade Openness": {"init": 50, "connections": {"Economic Growth": 0.3, "Global Energy Prices": 0.2}},
        "Inflation Rate": {"init": 50, "connections": {"Interest Rates": 0.7, "Economic Growth": -0.2, "Unemployment Rate": 0.3}},
        "Interest Rates": {"init": 40, "connections": {"Inflation Rate": 0.6, "Stock Market Volatility": 0.5, "Foreign Direct Investment": -0.3}},
        "Stock Market Volatility": {"init": 60, "connections": {"Foreign Direct Investment": -0.7, "Interest Rates": 0.5}},
        "Foreign Direct Investment": {"init": 50, "connections": {"Economic Growth": 0.4, "Tech Innovation Rate": 0.3}},
    },
    "Society": {
        "Population Growth": {"init": 60, "connections": {"Urbanization Rate": 0.5, "Resource Scarcity": 0.3, "Healthcare Access": -0.2}},
        "Urbanization Rate": {"init": 55, "connections": {"Air Quality": -0.4, "Social Stability": -0.2}},
        "Healthcare Access": {"init": 40, "connections": {"Life Expectancy": 0.8, "Social Stability": 0.3, "Public Trust in Institutions": 0.2}},
        "Education Access": {"init": 50, "connections": {"Digital Literacy": 0.6, "Economic Growth": 0.4, "Civic Participation": 0.3}},
        "Social Stability": {"init": 50, "connections": {"Crime Rate": -0.6, "Public Trust in Institutions": 0.7, "Economic Growth": 0.2}},
        "Migration Rate": {"init": 45, "connections": {"Cultural Diversity": 0.8, "Social Stability": -0.3, "Economic Growth": 0.1}},
        "Crime Rate": {"init": 30, "connections": {"Social Stability": -0.6, "Income Inequality": 0.5}},
        "Civic Participation": {"init": 40, "connections": {"Social Stability": 0.4, "Government Transparency": 0.5, "Public Trust in Institutions": 0.6}},
        "Life Expectancy": {"init": 75, "connections": {"Healthcare Access": 0.8, "Air Quality": 0.4, "Obesity Rate": -0.3}},
        "Public Trust in Institutions": {"init": 35, "connections": {"Government Transparency": 0.7, "Social Stability": 0.5, "Civic Participation": 0.4}},
        "Cultural Diversity": {"init": 60, "connections": {"Social Connectedness": 0.4, "Social Stability": 0.2}},
    },
    "Politics & Governance": {
        "Military Spending": {"init": 60, "connections": {"International Cooperation": -0.4, "Economic Growth": -0.2, "Social Stability": -0.3}},
        "Government Transparency": {"init": 40, "connections": {"Corruption Perception": -0.9, "Public Trust in Institutions": 0.7, "International Cooperation": 0.2}},
        "Democratic Index": {"init": 50, "connections": {"Freedom of Press": 0.8, "Political Stability": 0.6, "Civic Participation": 0.5}},
        "Corruption Perception": {"init": 70, "connections": {"Government Transparency": -0.9, "Foreign Direct Investment": -0.5, "Public Trust in Institutions": -0.8}},
        "International Cooperation": {"init": 50, "connections": {"Global Temperature": -0.2, "Economic Growth": 0.3, "Political Stability": 0.4}},
        "Freedom of Press": {"init": 60, "connections": {"Democratic Index": 0.8, "Public Trust in Institutions": 0.3}},
        "Political Stability": {"init": 65, "connections": {"Foreign Direct Investment": 0.2, "Social Stability": 0.7, "Economic Growth": 0.1}},
        "Rule of Law": {"init": 55, "connections": {"Foreign Direct Investment": 0.4, "Economic Growth": 0.3, "Social Stability": 0.2}},
        "Regulatory Quality": {"init": 50, "connections": {"Industrial Output": 0.4, "Economic Growth": 0.2, "Innovation Rate": 0.3}},
        "Voice and Accountability": {"init": 45, "connections": {"Civic Participation": 0.6, "Social Stability": 0.4, "Government Transparency": 0.5}},
    },
    "Technology & Innovation": {
        "Tech Innovation Rate": {"init": 50, "connections": {"Economic Growth": 0.5, "Automation Penetration": 0.6, "Renewable Energy Tech": 0.4}},
        "AI Development": {"init": 40, "connections": {"Automation Penetration": 0.7, "Economic Growth": 0.3, "Cybersecurity Investment": 0.5}},
        "Cybersecurity Investment": {"init": 60, "connections": {"Digital Literacy": 0.4, "AI Development": 0.5, "Public Trust in Institutions": 0.3}},
        "Automation Penetration": {"init": 55, "connections": {"Unemployment Rate": 0.6, "Economic Growth": 0.4, "Tech Innovation Rate": 0.6}},
        "Space Exploration Funding": {"init": 20, "connections": {"Tech Innovation Rate": 0.2, "Scientific Research": 0.9}},
        "Digital Literacy": {"init": 50, "connections": {"Education Access": 0.6, "Internet Access": 0.8, "Tech Innovation Rate": 0.3}},
        "Internet Access": {"init": 70, "connections": {"Digital Literacy": 0.8, "Economic Growth": 0.2, "Social Connectedness": 0.4}},
        "Renewable Energy Tech": {"init": 45, "connections": {"Investment in Renewable Energy": 0.9, "Fossil Fuel Consumption": -0.5, "Energy Efficiency": 0.7}},
        "Biotechnology Development": {"init": 30, "connections": {"Healthcare Access": 0.6, "Agricultural Productivity": 0.5, "Ethical Considerations": -0.2}},
    },
    "Health & Epidemics": {
        "Global Pandemic Risk": {"init": 70, "connections": {"International Cooperation": -0.5, "Healthcare Access": -0.2, "Global Travel": 0.6}},
        "Vaccination Rate": {"init": 60, "connections": {"Global Pandemic Risk": -0.8, "Life Expectancy": 0.5, "Public Health Spending": 0.7}},
        "Antibiotic Resistance": {"init": 65, "connections": {"Healthcare Access": -0.4, "Global Pandemic Risk": 0.3, "Public Health Spending": 0.2}},
        "Obesity Rate": {"init": 50, "connections": {"Healthcare Access": -0.3, "Life Expectancy": -0.4, "Food Security": -0.2}},
        "Mental Health Index": {"init": 40, "connections": {"Healthcare Access": 0.4, "Social Stability": 0.3, "Work-Life Balance": 0.6}},
        "Access to Clean Water": {"init": 60, "connections": {"Healthcare Access": 0.7, "Food Security": 0.4, "Public Health Spending": 0.3}},
    },
    "Agriculture & Food": {
        "Food Security": {"init": 50, "connections": {"Population Growth": -0.3, "Sustainable Agriculture": 0.6, "Economic Growth": 0.2}},
        "Crop Yield": {"init": 60, "connections": {"Sustainable Farming Practices": 0.7, "Agricultural Land Use": -0.2, "Food Security": 0.5}},
        "Agricultural Land Use": {"init": 40, "connections": {"Deforestation Rate": 0.5, "Water Usage": 0.7, "Species Biodiversity": -0.3}},
        "Meat Consumption": {"init": 70, "connections": {"Carbon Emissions": 0.4, "Agricultural Land Use": 0.3, "Healthcare Access": -0.2}},
        "Sustainable Farming Practices": {"init": 30, "connections": {"Crop Yield": 0.7, "Agricultural Land Use": -0.4, "Food Security": 0.6}},
        "Food Waste": {"init": 40, "connections": {"Food Security": -0.2, "Agricultural Land Use": 0.1, "Economic Growth": -0.1}},
    },
    "Culture & Wellbeing": {
        "Mental Health Index": {"init": 40, "connections": {"Social Connectedness": 0.7, "Work-Life Balance": 0.6, "Healthcare Access": 0.4}},
        "Work-Life Balance": {"init": 50, "connections": {"Economic Growth": -0.3, "Mental Health Index": 0.6, "Leisure Time": 0.8}},
        "Cultural Diversity": {"init": 60, "connections": {"Social Connectedness": 0.5, "Social Stability": 0.2, "Civic Participation": 0.3}},
        "Social Connectedness": {"init": 55, "connections": {"Mental Health Index": 0.7, "Cultural Diversity": 0.5, "Civic Participation": 0.4}},
        "Leisure Time": {"init": 50, "connections": {"Work-Life Balance": 0.8, "Mental Health Index": 0.3, "Economic Growth": 0.1}},
        "Arts and Culture Funding": {"init": 30, "connections": {"Cultural Diversity": 0.4, "Social Connectedness": 0.2, "Civic Participation": 0.3}},
    },
}